In [1]:
import numpy as np

In [3]:
vocabulary = np.load('./performance_zine/20250421_143517/vocab.npy')

In [5]:
print('Vocabulary size:', len(vocabulary))
print('Vocabulary:', vocabulary[:10])
print('type:', type(vocabulary))

Vocabulary size: 1000
Vocabulary: ['' '[UNK]' 'enfermedad' 'obesidad' 'asma' 'hipotiroidismo' 'leucocitos'
 'asma_no_especificada' 'dislipidemia' 'falla_respiratoria']
type: <class 'numpy.ndarray'>


In [6]:
X_train = np.load('./performance_zine/20250421_143517/X_train.npy')

In [7]:
print("X_train shape:", X_train.shape)
print("ten first elements of X_train:", X_train[:10])
print("type:", type(X_train))

X_train shape: (306, 4)
ten first elements of X_train: [[548 548 764 211]
 [457   2   1 358]
 [441 170   1   1]
 [186 119 320   1]
 [ 15  57   2  57]
 [707 403 624 624]
 [  7   7   7  13]
 [911 154 882   1]
 [527 161  18   2]
 [ 34   3   3   3]]
type: <class 'numpy.ndarray'>


In [ ]:
print(X_train[0])
X_seq = []
patient_n = 7
for i in range(len(X_train[patient_n])):
    number = X_train[patient_n][i]
    enf = vocabulary[number]
    X_seq.append(enf)
print(X_seq)

[548 548 764 211]
['examen_de_pesquisa_especial_para_tumor_de_la_mama', 'ateromatosis', 'leucoencefalopatía', '[UNK]']
